# Generated by Django 3.2.3 on 2021-05-19 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='本名'),
        ),
        migrations.AddField(
            model_name='user',
            name='history',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='農業歴'),
        ),
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='紹介文'),
        ),
        migrations.AddField(
            model_name='user',
            name='item',
            field=models.TextField(blank=True, default='', max_length=100, null=True, verbose_name='栽培品目'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
