# Generated by Django 3.2.3 on 2021-05-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210519_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='history',
            new_name='career',
        ),
    ]
