# Generated by Django 3.2.3 on 2021-05-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_history_user_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
